### ISSUE TITLE
need to include tailwind css cdn ?

### ISSUE THREAD

**Issue by Chandler-Zhu** [beyondcode/tailwindcss-jit-cdn#4]
When I use this tool do I also need to include a Tailwind CSS cdn like 
`<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet"> <script src="https://unpkg.com/tailwindcss-jit-cdn"></script>
`

**Comment by mpociot** [comment]
No, you don't need to include additional CSS as it will be generated on the fly by the JS library

**Comment by Chandler-Zhu** [comment]
Does it generate the css based on tailwind css v2.2 ?
